services:
  backend:
    platform: linux/amd64
    user: "1000:1000"
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mon-app
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
    - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - NODE_ENV=development

  python_env:
    platform: linux/amd64
    user: "1000:1000"
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python_app
    volumes:
      - ./python:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    networks:
      - app-network
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: bash 


  mongo:
    image: mongo:6
    platform: linux/amd64
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --bind_ip_all
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
